<?php

/**
 * Implements hook_permission().
 */
function custom_events_permission() {
    return array(
        'Custom Events Form' => array(
            'description' => t('Assign/display events form to user'),
            'title' => t('Assign/display events form'),
        ),
    );
}

/**
 * Implements hook_node_info().
 */
function custom_events_node_info() {
   return array(
        'custom_events' => array(
            'name' => t('Custom Events'),
            'base' => 'custom_events',
            'description' => t('Use for create custom events.'),
            'has_title' => TRUE,
            'title_label' => t('Event Title'),
            'custom' => 1,
            'modified' => 1,
            'locked' => 0,
            'comment' => array(
                'status' => 1,
                'default-mode' => 0,
            ),
        )
    );
}

/**
 * Implements hook_form().
 */
function custom_events_form($node, &$form_state) {
    return node_content_form($node, $form_state);
}

/**
 * Implements hook_views_api(). 
 */ 
function custom_events_views_api() { 
    return array(
        'api' => '3.0', 
        'path' => drupal_get_path('module', 'custom_events') . '/views' 
    ); 
}


/**
* Implements hook_views_default_views().
**/
function custom_events_views_default_views() {
    $files = file_scan_directory(drupal_get_path('module', 'custom_events'). '/views', '/.view/');
    foreach ($files as $filepath => $file) {
        require $filepath;
      if (isset($view)) {
            $views[$view->name] = $view;
      }
    }
    if ($views) {
        return $views;
    }
}